### PR TITLE
Add GitLab CI support

### PR DESCRIPTION
**Pull request by tuncer**
This is for use in the GitLab mirror at https://gitlab.com/triqng/triq.

### CODE REVIEW

**Comment by zkessin** [comment]
Should it also run dialyzer?

**Comment by tuncer** [comment]
> Should it also run dialyzer?

If it can be made fast enough, then yes.

**Comment by zkessin** [comment]
on some of my projects it is pretty fast, but I pre generate and cache the PLT file, not sure if gitlab can do that

**Comment by tuncer** [comment]
I'm actually expanding and improving gitlab-ci.yml right now.

**Comment by tuncer** [comment]
See https://github.com/triqng/triq/pull/18

**Pull request merged**
