### PR TITLE
Fix type definition of triq_dom:domrec/1

### PR DESCRIPTION
**Pull request by KrzysiekJ**

### CODE REVIEW

**Comment by KrzysiekJ** [comment]
The distinction between the two boolean values is already made in the record definition, in terms of field names. The reason that the record definition is not directly used in the type definition is likely that there seems to be now way to parameterize record definition.

**Comment by tuncer** [comment]
There was only one boolean field before and, if it's possible there will be more, it would make sense to bundle at least the new flags in a proplist. We cannot replace the empty_ok, but folding the new boolean into a proplist (for potential future expansion) makes sense.

**Comment by KrzysiekJ** [comment]
We can also remove the `noshrink` field altogether and instead allow the `shrink` field to take `none` values.

Another possible improvement is to add another fun/plain field to domain that will tell how many shrink attempts should be performed on a domain. Currently some shrink-related functions (`shrink_pair`, `shrink_list_samesize`, `shrink_tuple_samesize`, `shrink_list_members_generic`, `shrink_without_duplicates`) have bundled loops with hard-coded number of iterations and there is [an additional, hard-coded number of iterations for every shrinking function](https://github.com/triqng/triq/blob/5dbce6bf8848d5e2f46362a7832e0f9b70eeffb5/src/triq_dom.erl#L40-L41) (not to mention [the hard-coded number of iterations for every `?SUCHTHAT` loop](https://github.com/triqng/triq/blob/5dbce6bf8848d5e2f46362a7832e0f9b70eeffb5/src/triq.erl#L23-L27)). Handling additional looping not by the shrinking function internal to domain, but by the general shrinking function would make it easier to possibly parameterize how hard we try to shrink in general. Not sure how feasible this is though.

**Comment by tuncer** [comment]
Those are all good alternatives. Would any of them break the user API? If not, let's choose the best and implement it before the next release. Your pick?

**Comment by KrzysiekJ** [comment]
Haven’t analyzed what is better, but implemented the first variant in #64, as it’s simpler.

**Comment by tuncer** [comment]
Aren't we providing the same flexibility by giving the option to specify a custom function?

**Comment by tuncer** [comment]
Isn't #64 providing the same flexibility by allowing to specify a custom function?

**Comment by tuncer** [comment]
Doesn't #64 achieve the same flexibility by allowing to specify a custom function?

**Pull request merged**
